### ISSUE TITLE
default rake task fails running :package, :package works fine in isolation

### ISSUE THREAD

**Issue by stepheneb** [madrobby/scripty2#2]
Using git clone of repo and ruby 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0].

Running the default rake task which executes:

```
[:clean, :dist, :unified, :doc, :package, :clean_package_source]
```

fails running the :package task with this error:

```
** Invoke package (first_time)
** Invoke /Users/stephen/dev/javascript/scripty2-git/pkg/scripty2-2.0.0_a4.tar.gz (first_time)
** Invoke /Users/stephen/dev/javascript/scripty2-git/pkg/scripty2-2.0.0_a4 (first_time)
rake aborted!
Don't know how to build task 'README.rdoc'
```

Running:

```
rake package
```

by itself works fine.

**Comment by frekw** [comment]
It's not the actual rake task, but rather the packaging code starting at line 182 in the Rakefile. Haven't found a solution yet.

**Comment by clupprich** [comment]
Bugged me too. The reason is that there was a patch to pdoc (https://github.com/tobie/pdoc/commit/ad5113b45d924c276710b2712bcbe6dff9b9e6b7), which restores the current directory once pdoc has generated the documentation. This is not reflected in scripty2 until now, you need to update the pdoc submodule. I prepared a pull request which will incorporate this change.

**Comment by clupprich** [comment]
Okay, doesn't work like I said. pdoc has changed a lot during the commits, you'll better change the two lines in vendor/pdoc or live with rake && rake package. Sorry!
